import { getDb } from "../api/queries/connection";
import { categories, products } from "./schema";

const categoryData = [
  { slug: "bolas", name: "Rodamientos de Bolas", description: "Rodamientos de bolas de contacto radial profundo para aplicaciones universales", icon: "CircleDot" },
  { slug: "rodillos", name: "Rodamientos de Rodillos", description: "Rodamientos de rodillos cilíndricos para cargas radiales elevadas", icon: "Grip" },
  { slug: "conicos", name: "Rodamientos Cónicos", description: "Rodamientos de rodillos cónicos para cargas combinadas", icon: "Cone" },
  { slug: "esfericos", name: "Rodamientos Esféricos", description: "Rodamientos de rodillos esféricos para alineación automática", icon: "Sphere" },
  { slug: "empuje", name: "Rodamientos de Empuje", description: "Rodamientos axiales de bolas para cargas unidireccionales", icon: "ArrowDownToDot" },
  { slug: "agujas", name: "Rodamientos de Agujas", description: "Rodamientos de agujas compactos para espacio reducido", icon: "AlignJustify" },
];

const productData = [
  { sku: "6205-2RS/C3", name: "Rodamiento de Bolas 6205-2RS/C3", slug: "rodamiento-bolas-6205-2rs-c3", description: "Rodamiento de bolas de contacto radial profundo con sello de goma a ambos lados y juego interno C3. Ideal para motores eléctricos, bombas y cajas de cambios.", shortDescription: "Bolas radial profundo, sellos 2RS, juego C3. Para motores y bombas.", price: "12.50", oldPrice: "15.80", categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 342, rating: "4.8", reviewCount: 47, bestSeller: 1, brand: "SKF", tags: "motor,bomba,caja-cambios,sellado", specs: JSON.stringify({ "Diámetro interior": "25 mm", "Diámetro exterior": "52 mm", "Ancho": "15 mm", "Peso": "0.128 kg", "Velocidad max.": "14,000 rpm", "Carga dinámica": "14.0 kN", "Carga estática": "7.85 kN", "Sellos": "2RS (goma)", "Juego": "C3" }) },
  { sku: "6308-ZZ", name: "Rodamiento de Bolas 6308-ZZ", slug: "rodamiento-bolas-6308-zz", description: "Rodamiento de bolas de gran tamaño con escudos metálicos a ambos lados. Excelente para maquinaria industrial pesada, cintas transportadoras y ventiladores industriales.", shortDescription: "Bolas radial, escudos ZZ, alta carga. Maquinaria industrial.", price: "28.90", oldPrice: "34.50", categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 156, rating: "4.7", reviewCount: 32, bestSeller: 1, brand: "SKF", tags: "industrial,transportador,ventilador,pesado", specs: JSON.stringify({ "Diámetro interior": "40 mm", "Diámetro exterior": "90 mm", "Ancho": "23 mm", "Peso": "0.639 kg", "Velocidad max.": "9,000 rpm", "Carga dinámica": "40.5 kN", "Carga estática": "24.0 kN", "Sellos": "ZZ (metal)", "Juego": "Normal" }) },
  { sku: "6004-2RSH", name: "Rodamiento de Bolas 6004-2RSH", slug: "rodamiento-bolas-6004-2rsh", description: "Rodamiento de bolas serie 6000 con sellos de contacto HNBR para ambientes húmedos. Perfecto para aplicaciones de lavado industrial y procesamiento de alimentos.", shortDescription: "Bolas sellos HNBR, resistente agua. Procesos húmedos.", price: "8.40", oldPrice: "10.20", categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 89, rating: "4.6", reviewCount: 23, bestSeller: 1, brand: "FAG", tags: "humedad,alimentacion,pequeno,economico", specs: JSON.stringify({ "Diámetro interior": "20 mm", "Diámetro exterior": "42 mm", "Ancho": "12 mm", "Peso": "0.069 kg", "Velocidad max.": "17,000 rpm", "Carga dinámica": "9.95 kN", "Carga estática": "5.00 kN", "Sellos": "2RSH", "Juego": "Normal" }) },
  { sku: "6314-C3", name: "Rodamiento de Bolas 6314-C3", slug: "rodamiento-bolas-6314-c3", description: "Rodamiento de bolas de alta capacidad con juego interno C3 para temperaturas elevadas. Utilizado en motores de gran potencia, cajas de reducción industriales y equipos mineros.", shortDescription: "Bolas gran capacidad, juego C3. Alta temperatura.", price: "65.00", oldPrice: "78.00", categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 67, rating: "4.9", reviewCount: 15, bestSeller: 1, brand: "NSK", tags: "alta-temperatura,mineria,gran-potencia", specs: JSON.stringify({ "Diámetro interior": "70 mm", "Diámetro exterior": "150 mm", "Ancho": "35 mm", "Peso": "2.55 kg", "Velocidad max.": "6,300 rpm", "Carga dinámica": "111 kN", "Carga estática": "68.0 kN", "Sellos": "Abierto", "Juego": "C3" }) },
  { sku: "6206-2RS1/C3GJN", name: "Rodamiento 6206-2RS1/C3GJN", slug: "rodamiento-bolas-6206-2rs1-c3gjn", description: "Rodamiento de bolas con grasa poliurea de larga duración y juego C3. Vida útil extendida para aplicaciones de mantenimiento difícil. Excelente para HVAC y compresores.", shortDescription: "Grasa larga duración, juego C3. HVAC y compresores.", price: "18.30", oldPrice: null, categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 203, rating: "4.7", reviewCount: 38, bestSeller: 1, brand: "SKF", tags: "hvac,compresor,larga-vida", specs: JSON.stringify({ "Diámetro interior": "30 mm", "Diámetro exterior": "62 mm", "Ancho": "16 mm", "Peso": "0.199 kg", "Velocidad max.": "12,000 rpm", "Carga dinámica": "20.3 kN", "Carga estática": "11.2 kN", "Sellos": "2RS1", "Juego": "C3" }) },
  { sku: "6310-2Z/C3WT", name: "Rodamiento 6310-2Z/C3WT", slug: "rodamiento-bolas-6310-2z-c3wt", description: "Rodamiento de bolas con escudos metálicos y grasa de alta temperatura WT (hasta 160°C). Ideal para hornos industriales, secadores y aplicaciones térmicas.", shortDescription: "Alta temperatura WT, escudos Z. Hornos y secadores.", price: "42.80", oldPrice: null, categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 45, rating: "4.5", reviewCount: 19, bestSeller: 1, brand: "NTN", tags: "alta-temperatura,horno,secador", specs: JSON.stringify({ "Diámetro interior": "50 mm", "Diámetro exterior": "110 mm", "Ancho": "27 mm", "Peso": "1.07 kg", "Velocidad max.": "8,500 rpm", "Carga dinámica": "62.0 kN", "Carga estática": "38.0 kN", "Sellos": "2Z", "Juego": "C3" }) },
  { sku: "608-2RSH/C3", name: "Rodamiento Miniatura 608-2RSH/C3", slug: "rodamiento-bolas-608-2rsh-c3", description: "Rodamiento miniatura de bolas con sellos de goma. Extremadamente versátil para electrodomésticos, herramientas eléctricas, patines y maquinaria ligera.", shortDescription: "Miniatura 608, sellos goma. Herramientas y electrodomésticos.", price: "3.90", oldPrice: null, categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 500, rating: "4.6", reviewCount: 62, bestSeller: 1, brand: "SKF", tags: "miniatura,herramienta,electrodomestico", specs: JSON.stringify({ "Diámetro interior": "8 mm", "Diámetro exterior": "22 mm", "Ancho": "7 mm", "Peso": "0.012 kg", "Velocidad max.": "36,000 rpm", "Carga dinámica": "3.45 kN", "Carga estática": "1.37 kN", "Sellos": "2RSH", "Juego": "C3" }) },
  { sku: "6320/C3", name: "Rodamiento de Bolas 6320/C3", slug: "rodamiento-bolas-6320-c3", description: "Rodamiento de bolas de gran tamaño, abierto, juego C3. Para aplicaciones de alta carga en molinos, trituradoras y maquinaria pesada de construcción.", shortDescription: "Bolas gran tamaño, juego C3. Molinos y trituradoras.", price: "185.00", oldPrice: null, categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 23, rating: "4.8", reviewCount: 8, bestSeller: 1, brand: "TIMKEN", tags: "gran-tamano,molino,trituradora,pesado", specs: JSON.stringify({ "Diámetro interior": "100 mm", "Diámetro exterior": "215 mm", "Ancho": "47 mm", "Peso": "6.98 kg", "Velocidad max.": "4,300 rpm", "Carga dinámica": "174 kN", "Carga estática": "140 kN", "Sellos": "Abierto", "Juego": "C3" }) },
  { sku: "6010-2RS", name: "Rodamiento de Bolas 6010-2RS", slug: "rodamiento-bolas-6010-2rs", description: "Rodamiento de bolas serie 6010 con sellos de goma. Equilibrio perfecto entre tamaño y capacidad de carga para maquinaria general.", shortDescription: "Bolas serie 6010, sellos 2RS. Maquinaria general.", price: "15.60", oldPrice: null, categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 178, rating: "4.4", reviewCount: 27, bestSeller: 0, brand: "FAG", tags: "general,mediano", specs: JSON.stringify({ "Diámetro interior": "50 mm", "Diámetro exterior": "80 mm", "Ancho": "16 mm", "Peso": "0.261 kg", "Velocidad max.": "9,500 rpm", "Carga dinámica": "21.2 kN", "Carga estática": "15.0 kN", "Sellos": "2RS", "Juego": "Normal" }) },
  { sku: "6208-2Z/C3", name: "Rodamiento de Bolas 6208-2Z/C3", slug: "rodamiento-bolas-6208-2z-c3", description: "Rodamiento de bolas con escudos metálicos y juego C3. Para motores industriales, reductores y bombas centrífugas.", shortDescription: "Escudos ZZ, juego C3. Motores y reductores.", price: "22.40", oldPrice: null, categorySlug: "bolas", category: "Rodamientos de Bolas", imageUrl: "/assets/bearing-ball.png", stock: 134, rating: "4.5", reviewCount: 21, bestSeller: 0, brand: "NSK", tags: "motor,reductor", specs: JSON.stringify({ "Diámetro interior": "40 mm", "Diámetro exterior": "80 mm", "Ancho": "18 mm", "Peso": "0.37 kg", "Velocidad max.": "9,500 rpm", "Carga dinámica": "32.5 kN", "Carga estática": "19.0 kN", "Sellos": "2Z", "Juego": "C3" }) },
  { sku: "NU2205-E-XL-TVP2", name: "Rodamiento Rodillos NU2205-E-XL", slug: "rodamiento-rodillos-nu2205-e-xl", description: "Rodamiento de rodillos cilíndricos con jaula de poliamida reforzada. Capacidad de carga radial superior. Ideal para cajas de engranajes y ejes de transmisión.", shortDescription: "Rodillos cilíndricos, jaula poliamida. Cajas engranajes.", price: "35.50", oldPrice: "42.00", categorySlug: "rodillos", category: "Rodamientos de Rodillos", imageUrl: "/assets/bearing-roller.png", stock: 78, rating: "4.7", reviewCount: 14, bestSeller: 1, brand: "FAG", tags: "caja-engranajes,eje-transmision,carga-radial", specs: JSON.stringify({ "Diámetro interior": "25 mm", "Diámetro exterior": "52 mm", "Ancho": "18 mm", "Peso": "0.168 kg", "Velocidad max.": "15,000 rpm", "Carga dinámica": "32.0 kN", "Carga estática": "27.5 kN", "Tipo": "NU (anillo desmontable)", "Jaula": "PA66-GF25" }) },
  { sku: "NU310-E-XL-M1", name: "Rodamiento Rodillos NU310-E-XL-M1", slug: "rodamiento-rodillos-nu310-e-xl-m1", description: "Rodamiento de rodillos cilíndricos con jaula de latón macizo. Alta capacidad de carga para aplicaciones pesadas de laminación y minería.", shortDescription: "Rodillos cilíndricos, jaula latón. Minería y laminación.", price: "89.00", oldPrice: null, categorySlug: "rodillos", category: "Rodamientos de Rodillos", imageUrl: "/assets/bearing-roller.png", stock: 34, rating: "4.8", reviewCount: 9, bestSeller: 1, brand: "FAG", tags: "mineria,laminacion,pesado", specs: JSON.stringify({ "Diámetro interior": "50 mm", "Diámetro exterior": "110 mm", "Ancho": "27 mm", "Peso": "1.15 kg", "Velocidad max.": "8,000 rpm", "Carga dinámica": "130 kN", "Carga estática": "112 kN", "Tipo": "NU", "Jaula": "Latón M1" }) },
  { sku: "NUP207-E-XL-TVP2", name: "Rodamiento Rodillos NUP207-E-XL", slug: "rodamiento-rodillos-nup207-e-xl", description: "Rodamiento de rodillos cilíndricos con pestaña de guía. Permite carga axial en ambas direcciones. Para husillos de máquinas herramienta.", shortDescription: "Rodillos con pestaña guía. Husillos máquinas herramienta.", price: "48.70", oldPrice: null, categorySlug: "rodillos", category: "Rodamientos de Rodillos", imageUrl: "/assets/bearing-roller.png", stock: 56, rating: "4.5", reviewCount: 11, bestSeller: 0, brand: "FAG", tags: "husillo,maquina-herramienta", specs: JSON.stringify({ "Diámetro interior": "35 mm", "Diámetro exterior": "72 mm", "Ancho": "17 mm", "Peso": "0.307 kg", "Velocidad max.": "11,000 rpm", "Carga dinámica": "56.0 kN", "Carga estática": "46.0 kN", "Tipo": "NUP", "Jaula": "PA66" }) },
  { sku: "NJ2308-E-XL-TVP2", name: "Rodamiento Rodillos NJ2308-E-XL", slug: "rodamiento-rodillos-nj2308-e-xl", description: "Rodamiento de rodillos cilíndricos de gran tamaño con jaula de poliamida. Para turbinas eólicas, generadores y cajas de engranajes industriales.", shortDescription: "Rodillos gran tamaño, jaula poliamida. Turbinas eólicas.", price: "145.00", oldPrice: null, categorySlug: "rodillos", category: "Rodamientos de Rodillos", imageUrl: "/assets/bearing-roller.png", stock: 19, rating: "4.9", reviewCount: 6, bestSeller: 1, brand: "SKF", tags: "eolica,generador,gran-tamano", specs: JSON.stringify({ "Diámetro interior": "40 mm", "Diámetro exterior": "90 mm", "Ancho": "33 mm", "Peso": "0.95 kg", "Velocidad max.": "8,500 rpm", "Carga dinámica": "131 kN", "Carga estática": "120 kN", "Tipo": "NJ", "Jaula": "PA66-GF25" }) },
  { sku: "NU1007-M1", name: "Rodamiento Rodillos NU1007-M1", slug: "rodamiento-rodillos-nu1007-m1", description: "Rodamiento de rodillos cilíndricos de alta precisión con jaula de latón. Para aplicaciones de alta velocidad en equipos de automatización.", shortDescription: "Rodillos alta precisión, jaula latón. Automatización.", price: "62.30", oldPrice: null, categorySlug: "rodillos", category: "Rodamientos de Rodillos", imageUrl: "/assets/bearing-roller.png", stock: 42, rating: "4.4", reviewCount: 7, bestSeller: 0, brand: "NSK", tags: "automatizacion,alta-velocidad", specs: JSON.stringify({ "Diámetro interior": "35 mm", "Diámetro exterior": "62 mm", "Ancho": "14 mm", "Peso": "0.179 kg", "Velocidad max.": "14,000 rpm", "Carga dinámica": "35.5 kN", "Carga estática": "31.0 kN", "Tipo": "NU", "Jaula": "Latón M1" }) },
  { sku: "SL182210-A-XL", name: "Rodamiento Rodillos SL182210", slug: "rodamiento-rodillos-sl182210", description: "Rodamiento de rodillos cilíndricos de complemento completo (sin jaula). Máxima capacidad de carga para prensas y cilindros hidráulicos.", shortDescription: "Complemento completo, sin jaula. Prensas hidráulicas.", price: "78.90", oldPrice: null, categorySlug: "rodillos", category: "Rodamientos de Rodillos", imageUrl: "/assets/bearing-roller.png", stock: 28, rating: "4.7", reviewCount: 5, bestSeller: 0, brand: "INA", tags: "prensa,hidraulico,carga-maxima", specs: JSON.stringify({ "Diámetro interior": "50 mm", "Diámetro exterior": "90 mm", "Ancho": "23 mm", "Peso": "0.60 kg", "Velocidad max.": "5,500 rpm", "Carga dinámica": "108 kN", "Carga estática": "134 kN", "Tipo": "SL18 (complemento)", "Jaula": "Sin jaula" }) },
  { sku: "30208-A", name: "Rodamiento Cónico 30208-A", slug: "rodamiento-conico-30208-a", description: "Rodamiento de rodillos cónicos de una hilera. Diseñado para soportar cargas combinadas radiales y axiales. Ideal para ruedas de automoción y cajas de cambios.", shortDescription: "Cónico una hilera. Ruedas y cajas de cambios.", price: "18.90", oldPrice: "22.50", categorySlug: "conicos", category: "Rodamientos Cónicos", imageUrl: "/assets/bearing-tapered.png", stock: 112, rating: "4.6", reviewCount: 29, bestSeller: 1, brand: "FAG", tags: "automocion,rueda,caja-cambios", specs: JSON.stringify({ "Diámetro interior": "40 mm", "Diámetro exterior": "80 mm", "Ancho total": "19.75 mm", "Peso": "0.42 kg", "Velocidad max.": "9,000 rpm", "Carga dinámica": "60.5 kN", "Carga estática": "63.0 kN", "Angulo": "18.5°", "Separable": "Sí" }) },
  { sku: "32011-X", name: "Rodamiento Cónico 32011-X", slug: "rodamiento-conico-32011-x", description: "Rodamiento de rodillos cónicos serie 32000 para cargas radiales moderadas. Usado en diferenciales, ejes de transmisión y maquinaria agrícola.", shortDescription: "Cónico serie 32000. Diferenciales y maquinaria agrícola.", price: "24.50", oldPrice: null, categorySlug: "conicos", category: "Rodamientos Cónicos", imageUrl: "/assets/bearing-tapered.png", stock: 67, rating: "4.5", reviewCount: 16, bestSeller: 1, brand: "TIMKEN", tags: "diferencial,agricola,eje", specs: JSON.stringify({ "Diámetro interior": "55 mm", "Diámetro exterior": "90 mm", "Ancho total": "23 mm", "Peso": "0.58 kg", "Velocidad max.": "7,500 rpm", "Carga dinámica": "80.2 kN", "Carga estática": "116 kN", "Angulo": "14°", "Separable": "Sí" }) },
  { sku: "30309-A", name: "Rodamiento Cónico 30309-A", slug: "rodamiento-conico-30309-a", description: "Rodamiento de rodillos cónicos de gran capacidad con ángulo mayor. Para aplicaciones con carga axial significativa como cajas de cambios de camiones.", shortDescription: "Cónico gran capacidad. Cajas cambios camiones.", price: "32.80", oldPrice: null, categorySlug: "conicos", category: "Rodamientos Cónicos", imageUrl: "/assets/bearing-tapered.png", stock: 48, rating: "4.7", reviewCount: 12, bestSeller: 0, brand: "FAG", tags: "camion,carga-axial,pesado", specs: JSON.stringify({ "Diámetro interior": "45 mm", "Diámetro exterior": "100 mm", "Ancho total": "27.25 mm", "Peso": "0.98 kg", "Velocidad max.": "6,500 rpm", "Carga dinámica": "112 kN", "Carga estática": "125 kN", "Angulo": "24°", "Separable": "Sí" }) },
  { sku: "32215-XL", name: "Rodamiento Cónico 32215-XL", slug: "rodamiento-conico-32215-xl", description: "Rodamiento de rodillos cónicos de gran tamaño para industria metalúrgica. Soporta cargas extremas en laminadores y prensas forjadoras.", shortDescription: "Cónico gran tamaño. Metalurgia y laminación.", price: "95.00", oldPrice: null, categorySlug: "conicos", category: "Rodamientos Cónicos", imageUrl: "/assets/bearing-tapered.png", stock: 15, rating: "4.9", reviewCount: 4, bestSeller: 0, brand: "TIMKEN", tags: "metalurgia,laminador,forja,extremo", specs: JSON.stringify({ "Diámetro interior": "75 mm", "Diámetro exterior": "130 mm", "Ancho total": "33.25 mm", "Peso": "1.72 kg", "Velocidad max.": "4,800 rpm", "Carga dinámica": "175 kN", "Carga estática": "250 kN", "Angulo": "16.5°", "Separable": "Sí" }) },
  { sku: "22208-E-XL-K-C3", name: "Rodamiento Esférico 22208-E-XL-K-C3", slug: "rodamiento-esferico-22208-e-xl-k-c3", description: "Rodamiento de rodillos esféricos con orificio cónico (1:12) y juego C3. Autocompensador de desalineación. Ideal para sistemas de vibración, transportadores y maquinaria minera.", shortDescription: "Esférico autocompensador, orificio cónico. Vibración y minería.", price: "55.00", oldPrice: "65.00", categorySlug: "esfericos", category: "Rodamientos Esféricos", imageUrl: "/assets/bearing-spherical.png", stock: 38, rating: "4.7", reviewCount: 13, bestSeller: 1, brand: "FAG", tags: "autocompensador,vibracion,mineria,transportador", specs: JSON.stringify({ "Diámetro interior": "40 mm", "Diámetro exterior": "80 mm", "Ancho": "23 mm", "Peso": "0.53 kg", "Velocidad max.": "8,000 rpm", "Carga dinámica": "106 kN", "Carga estática": "102 kN", "Autocompensación": "2°", "Orificio": "Cónico K" }) },
  { sku: "22310-E-XL-C3", name: "Rodamiento Esférico 22310-E-XL-C3", slug: "rodamiento-esferico-22310-e-xl-c3", description: "Rodamiento de rodillos esféricos de gran capacidad con juego C3. Para equipos de cribado, trituradoras y bombas de lodo con alta vibración.", shortDescription: "Esférico gran capacidad, juego C3. Cribado y trituración.", price: "92.00", oldPrice: null, categorySlug: "esfericos", category: "Rodamientos Esféricos", imageUrl: "/assets/bearing-spherical.png", stock: 22, rating: "4.8", reviewCount: 8, bestSeller: 1, brand: "SKF", tags: "cribado,trituradora,bomba-lodo", specs: JSON.stringify({ "Diámetro interior": "50 mm", "Diámetro exterior": "110 mm", "Ancho": "40 mm", "Peso": "1.85 kg", "Velocidad max.": "5,500 rpm", "Carga dinámica": "204 kN", "Carga estática": "196 kN", "Autocompensación": "2°", "Orificio": "Cilíndrico" }) },
  { sku: "22218-E-XL-K", name: "Rodamiento Esférico 22218-E-XL-K", slug: "rodamiento-esferico-22218-e-xl-k", description: "Rodamiento de rodillos esféricos de gran tamaño con orificio cónico. Para ejes de molinos, tambores de elevadores y maquinaria pesada con desalineación.", shortDescription: "Esférico gran tamaño, orificio cónico. Molinos y elevadores.", price: "210.00", oldPrice: null, categorySlug: "esfericos", category: "Rodamientos Esféricos", imageUrl: "/assets/bearing-spherical.png", stock: 9, rating: "4.9", reviewCount: 3, bestSeller: 0, brand: "FAG", tags: "molino,elevador,gran-tamano", specs: JSON.stringify({ "Diámetro interior": "90 mm", "Diámetro exterior": "160 mm", "Ancho": "40 mm", "Peso": "3.35 kg", "Velocidad max.": "4,000 rpm", "Carga dinámica": "285 kN", "Carga estática": "355 kN", "Autocompensación": "2°", "Orificio": "Cónico K" }) },
  { sku: "21306-E-XL-TVPB", name: "Rodamiento Esférico 21306-E-XL-TVPB", slug: "rodamiento-esferico-21306-e-xl-tvpb", description: "Rodamiento de rodillos esféricos serie 213 con jaula de poliamida. Compacto con alta capacidad para bombas y ventiladores industriales.", shortDescription: "Esférico compacto, jaula poliamida. Bombas y ventiladores.", price: "68.50", oldPrice: null, categorySlug: "esfericos", category: "Rodamientos Esféricos", imageUrl: "/assets/bearing-spherical.png", stock: 31, rating: "4.5", reviewCount: 6, bestSeller: 0, brand: "NSK", tags: "bomba,ventilador,compacto", specs: JSON.stringify({ "Diámetro interior": "30 mm", "Diámetro exterior": "72 mm", "Ancho": "19 mm", "Peso": "0.40 kg", "Velocidad max.": "9,500 rpm", "Carga dinámica": "64.0 kN", "Carga estática": "57.0 kN", "Autocompensación": "2°", "Orificio": "Cilíndrico" }) },
  { sku: "51104", name: "Rodamiento de Empuje 51104", slug: "rodamiento-empuje-51104", description: "Rodamiento de bolas de empuje de una sola dirección. Diseño plano compacto para mecanismos de ajuste y prensas. Capacidad axial moderada.", shortDescription: "Empuje bolas, una dirección. Mecanismos ajuste y prensas.", price: "14.20", oldPrice: "17.00", categorySlug: "empuje", category: "Rodamientos de Empuje", imageUrl: "/assets/bearing-ball.png", stock: 87, rating: "4.4", reviewCount: 18, bestSeller: 1, brand: "SKF", tags: "axial,ajuste,compacto", specs: JSON.stringify({ "Diámetro interior": "20 mm", "Diámetro exterior": "35 mm", "Ancho": "10 mm", "Peso": "0.039 kg", "Velocidad max.": "7,500 rpm", "Carga dinámica": "14.2 kN", "Carga estática": "24.5 kN", "Tipo": " axial bolas", "Dirección": "Una" }) },
  { sku: "51206", name: "Rodamiento de Empuje 51206", slug: "rodamiento-empuje-51206", description: "Rodamiento de bolas de empuje de gran tamaño. Para válvulas industriales, compresores reciprocantes y sistemas hidráulicos con alta carga axial.", shortDescription: "Empuje bolas gran tamaño. Válvulas y compresores.", price: "28.60", oldPrice: null, categorySlug: "empuje", category: "Rodamientos de Empuje", imageUrl: "/assets/bearing-ball.png", stock: 45, rating: "4.6", reviewCount: 9, bestSeller: 0, brand: "NSK", tags: "valvula,compresor,hidraulico", specs: JSON.stringify({ "Diámetro interior": "30 mm", "Diámetro exterior": "52 mm", "Ancho": "16 mm", "Peso": "0.12 kg", "Velocidad max.": "5,500 rpm", "Carga dinámica": "26.0 kN", "Carga estática": "50.0 kN", "Tipo": " axial bolas", "Dirección": "Una" }) },
  { sku: "NKIS35-XL", name: "Rodamiento de Agujas NKIS35-XL", slug: "rodamiento-agujas-nkis35-xl", description: "Rodamiento de agujas con aros interiores. Muy compacto con alta capacidad de carga radial. Ideal para cajas de cambios y bombas de engranajes.", shortDescription: "Agujas con aro interior, compacto. Cajas cambios y bombas.", price: "22.40", oldPrice: null, categorySlug: "agujas", category: "Rodamientos de Agujas", imageUrl: "/assets/bearing-needle.png", stock: 64, rating: "4.5", reviewCount: 11, bestSeller: 1, brand: "INA", tags: "compacto,caja-cambios,bomba-engranaje", specs: JSON.stringify({ "Diámetro interior": "35 mm", "Diámetro exterior": "58 mm", "Ancho": "22 mm", "Peso": "0.19 kg", "Velocidad max.": "11,000 rpm", "Carga dinámica": "34.5 kN", "Carga estática": "52.0 kN", "Con aro": "Sí", "Sellos": "Sin" }) },
  { sku: "NA4905-XL", name: "Rodamiento de Agujas NA4905-XL", slug: "rodamiento-agujas-na4905-xl", description: "Rodamiento de agujas con aros y jaula guiada. Para aplicaciones donde el espacio radial es limitado como en bielas y cigüeñales.", shortDescription: "Agujas con aros guiados. Bielas y cigüeñales.", price: "18.80", oldPrice: null, categorySlug: "agujas", category: "Rodamientos de Agujas", imageUrl: "/assets/bearing-needle.png", stock: 52, rating: "4.3", reviewCount: 14, bestSeller: 0, brand: "INA", tags: "biela,ciguenal,espacio-reducido", specs: JSON.stringify({ "Diámetro interior": "25 mm", "Diámetro exterior": "42 mm", "Ancho": "17 mm", "Peso": "0.094 kg", "Velocidad max.": "13,000 rpm", "Carga dinámica": "24.5 kN", "Carga estática": "34.0 kN", "Con aro": "Sí", "Jaula": "Guiada" }) },
  { sku: "HK4020-B", name: "Rodamiento de Agujas HK4020-B", slug: "rodamiento-agujas-hk4020-b", description: "Rodamiento de agujas de copa dibujada (sin aro interior). Extremadamente compacto para sistemas de dirección, embragues y freno.", shortDescription: "Agujas copa dibujada, sin aro. Dirección y embrague.", price: "9.50", oldPrice: null, categorySlug: "agujas", category: "Rodamientos de Agujas", imageUrl: "/assets/bearing-needle.png", stock: 120, rating: "4.4", reviewCount: 22, bestSeller: 1, brand: "INA", tags: "direccion,embrague,freno,compacto", specs: JSON.stringify({ "Diámetro interior": "40 mm (rótula)", "Diámetro exterior": "47 mm", "Ancho": "20 mm", "Peso": "0.048 kg", "Velocidad max.": "9,000 rpm", "Carga dinámica": "26.9 kN", "Carga estática": "55.0 kN", "Con aro": "No", "Tipo": "Copa dibujada" }) },
  { sku: "NKS45-XL", name: "Rodamiento de Agujas NKS45-XL", slug: "rodamiento-agujas-nks45-xl", description: "Rodamiento de agujas sin aro interior para ejes endurecidos. Alta capacidad de carga para sistemas hidráulicos y neumáticos.", shortDescription: "Agujas sin aro, eje endurecido. Hidráulico y neumático.", price: "15.60", oldPrice: null, categorySlug: "agujas", category: "Rodamientos de Agujas", imageUrl: "/assets/bearing-needle.png", stock: 37, rating: "4.2", reviewCount: 6, bestSeller: 0, brand: "INA", tags: "hidraulico,neumatico,eje-endurecido", specs: JSON.stringify({ "Diámetro interior": "45 mm (rótula)", "Diámetro exterior": "60 mm", "Ancho": "22 mm", "Peso": "0.14 kg", "Velocidad max.": "8,000 rpm", "Carga dinámica": "31.0 kN", "Carga estática": "60.0 kN", "Con aro": "No", "Tipo": "NKS" }) },
];

async function seed() {
  const db = getDb();
  console.log("Cleaning existing data...");
  await db.delete(products);
  await db.delete(categories);
  console.log("Seeding categories...");
  const insertedCategories = await db.insert(categories).values(categoryData).$returningId();
  const catMap = new Map<string, number>();
  categoryData.forEach((cat, i) => catMap.set(cat.slug, insertedCategories[i].id));

  console.log("Seeding products...");
  const productInserts = productData.map((p) => ({
    ...p,
    categoryId: catMap.get(p.categorySlug)!,
  }));

  const batchSize = 10;
  for (let i = 0; i < productInserts.length; i += batchSize) {
    const batch = productInserts.slice(i, i + batchSize);
    await db.insert(products).values(batch);
    console.log(`Inserted products ${i + 1} - ${Math.min(i + batchSize, productInserts.length)}`);
  }

  console.log("Seed complete!");
}

seed().catch(console.error);
